version: '3.1'
services:
  db:
    image: mongo:3.6
  backend:
    image: node:8.9.4
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && npm start"
  frontend:
    image: nginx:1.13.9
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8080:80
