version: '3.1'

services:
  nginx:
    image: nginx:1.17.8
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
