version: '3.7'
volumes:
  db_data:
services:
  db:
    image: postgres:11.5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  frontend:
    image: nginx:1.17.4
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8080:80
